In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import datetime as dt

In [2]:
df=pd.read_csv("/kaggle/input/datasets/abhigyanonly/event-driven/Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv")

In [3]:
df

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FKID000001,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,...,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",12.921876,77.645158,NaN,NaN,FKUSR00002,2024-01-30 04:17:46.828355+00,NaN,NaN,NaN
2,FKID000002,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 04:56:03.281509+00,NaN,NaN,Bengaluru Central Corporation,Central Zone 2,UrvashiJunction
3,FKID000003,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,...,NaN,NaN,NaN,FKUSR00004,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN,NaN,NaN
4,FKID000004,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 05:35:17.338283+00,NaN,NaN,NaN,NaN,LalbaghMainGateJunc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8168,FKID008168,unplanned,12.917775,77.600024,0.000000,0.000000,"Jayadeva BTM Underpass, Jayadeva Junction, BTM...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR01083,2024-01-29 21:32:37.883303+00,NaN,NaN,NaN,NaN,JayadevaHospitalJunc
8169,FKID008169,unplanned,12.890951,77.564757,0.000000,0.000000,"Konanakunte Main Road, Century Central, Naidu ...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR01486,2024-01-29 22:03:41.313223+00,NaN,NaN,NaN,NaN,KonanakunteJunction(KanakapurarRd)
8170,FKID008170,unplanned,12.916976,77.583443,0.000000,0.000000,"46th Cross Road, Adarsh Palace Apartment, TMC ...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR01992,2024-01-29 22:11:51.762767+00,NaN,NaN,NaN,NaN,Arbindo Circle
8171,FKID008171,unplanned,12.972042,77.619483,0.000000,0.000000,"Trinity Church Road, Trinity Circle, Ashok Nag...",NaN,pot_holes,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TrinityCircle
8172,FKID008172,unplanned,12.951953,77.589486,12.951903,77.589523,"Hosur Road, Lal Bagh Botanical Garden Area, Ma...","Hosur Road, Lal Bagh Botanical Garden Area, Ma...",vehicle_breakdown,True,...,NaN,NaN,NaN,FKUSR01675,2024-01-30 02:07:14.594818+00,NaN,NaN,NaN,NaN,K H Road-SiddaiahRdJunc(BMTC-BigBazaar)

In [4]:
df.columns

Index(['id', 'event_type', 'latitude', 'longitude', 'endlatitude',
       'endlongitude', 'address', 'end_address', 'event_cause',
       'requires_road_closure', 'start_datetime', 'end_datetime', 'status',
       'authenticated', 'modified_datetime', 'map_file', 'direction',
       'description', 'veh_type', 'veh_no', 'corridor', 'priority',
       'cargo_material', 'reason_breakdown', 'age_of_truck', 'created_date',
       'route_path', 'client_id', 'created_by_id', 'last_modified_by_id',
       'assigned_to_police_id', 'citizen_accident_id', 'comment',
       'police_station', 'meta_data', 'kgid', 'resolved_at_address',
       'resolved_at_latitude', 'resolved_at_longitude', 'closed_by_id',
       'closed_datetime', 'resolved_by_id', 'resolved_datetime',
       'gba_identifier', 'zone', 'junction'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8173 entries, 0 to 8172
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     8173 non-null   object
 1   event_type             8173 non-null   object
 2   latitude               8173 non-null   float64
 3   longitude              8173 non-null   float64
 4   endlatitude            8004 non-null   float64
 5   endlongitude           8004 non-null   float64
 6   address                8170 non-null   object
 7   end_address            687 non-null    object
 8   event_cause            8173 non-null   object
 9   requires_road_closure  8173 non-null   bool
 10  start_datetime         8173 non-null   object
 11  end_datetime           490 non-null    object
 12  status                 8173 non-null   object
 13  authenticated          8173 non-null   object
 14  modified_datetime      8173 non-null   object
 15  map_file               0 non-null      float64
 16  direction              43 non-null     object
 17  description            6813 non-null   object
 18  veh_type               4887 non-null   object
 19  veh_no                 4886 non-null   object
 20  corridor               8153 non-null   object
 21  priority               8171 non-null   object
 22  cargo_material         276 non-null    object
 23  reason_breakdown       276 non-null    object
 24  age_of_truck           276 non-null    float64
 25  created_date           8173 non-null   object
 26  route_path             137 non-null    object
 27  client_id              8173 non-null   int64
 28  created_by_id          8171 non-null   object
 29  last_modified_by_id    8170 non-null   object
 30  assigned_to_police_id  128 non-null    object
 31  citizen_accident_id    128 non-null    object
 32  comment                0 non-null      float64
 33  police_station         8173 non-null   object
 34  meta_data              0 non-null      float64
 35  kgid                   7914 non-null   object
 36  resolved_at_address    74 non-null     object
 37  resolved_at_latitude   74 non-null     float64
 38  resolved_at_longitude  74 non-null     float64
 39  closed_by_id           3141 non-null   object
 40  closed_datetime        3141 non-null   object
 41  resolved_by_id         74 non-null     object
 42  resolved_datetime      74 non-null     object
 43  gba_identifier         3444 non-null   object
 44  zone                   3444 non-null   object
 45  junction               2510 non-null   object
dtypes: bool(1), float64(10), int64(1), object(34)
memory usage: 2.8+ MB

In [6]:
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent.sort_values(ascending=False))

comment                  100.000000
map_file                 100.000000
meta_data                100.000000
direction                 99.473877
resolved_at_address       99.094580
resolved_at_latitude      99.094580
resolved_by_id            99.094580
resolved_datetime         99.094580
resolved_at_longitude     99.094580
assigned_to_police_id     98.433868
citizen_accident_id       98.433868
route_path                98.323749
age_of_truck              96.623027
reason_breakdown          96.623027
cargo_material            96.623027
end_datetime              94.004649
end_address               91.594274
junction                  69.289123
closed_datetime           61.568579
closed_by_id              61.568579
gba_identifier            57.861250
zone                      57.861250
veh_no                    40.217790
veh_type                  40.205555
description               16.640157
kgid                       3.168971
endlongitude               2.067784
endlatitude                2.067784
corridor                   0.244708
address                    0.036706
last_modified_by_id        0.036706
priority                   0.024471
created_by_id              0.024471
authenticated              0.000000
event_cause                0.000000
id                         0.000000
longitude                  0.000000
latitude                   0.000000
event_type                 0.000000
status                     0.000000
start_datetime             0.000000
requires_road_closure      0.000000
client_id                  0.000000
created_date               0.000000
modified_datetime          0.000000
police_station             0.000000
dtype: float64

In [7]:
drop_cols = [
    'comment', 'map_file', 'meta_data',
    'direction',
    'resolved_at_address',
    'resolved_at_latitude',
    'resolved_at_longitude',
    'resolved_by_id',
    'resolved_datetime',
    'assigned_to_police_id',
    'citizen_accident_id',
    'route_path',
    'age_of_truck',
    'reason_breakdown',
    'cargo_material',
    'end_address'
]

df = df.drop(columns=drop_cols)

In [8]:
df.columns

Index(['id', 'event_type', 'latitude', 'longitude', 'endlatitude',
       'endlongitude', 'address', 'event_cause', 'requires_road_closure',
       'start_datetime', 'end_datetime', 'status', 'authenticated',
       'modified_datetime', 'description', 'veh_type', 'veh_no', 'corridor',
       'priority', 'created_date', 'client_id', 'created_by_id',
       'last_modified_by_id', 'police_station', 'kgid', 'closed_by_id',
       'closed_datetime', 'gba_identifier', 'zone', 'junction'],
      dtype='object')

In [9]:
print(df['event_type'].value_counts())
print(df['event_cause'].value_counts().head(20))
print(df['priority'].value_counts())
print(df['status'].value_counts())
print(df['requires_road_closure'].value_counts())
print(df['event_type'].value_counts())

event_type
unplanned    7706
planned       467
Name: count, dtype: int64
event_cause
vehicle_breakdown       4896
others                   638
pot_holes                537
construction             480
water_logging            458
accident                 365
tree_fall                284
road_conditions          170
congestion               136
public_event              84
procession                72
vip_movement              20
protest                   15
Debris                    12
test_demo                  3
Fog / Low Visibility       2
debris                     1
Name: count, dtype: int64
priority
High    5030
Low     3141
Name: count, dtype: int64
status
closed      7095
active      1007
resolved      71
Name: count, dtype: int64
requires_road_closure
False    7497
True      676
Name: count, dtype: int64
event_type
unplanned    7706
planned       467
Name: count, dtype: int64

In [10]:
df['client_id'].nunique()

2

In [11]:
df['kgid'].nunique()

1853

In [12]:
df['event_cause'] = df['event_cause'].str.lower()

In [13]:
print(df['event_cause'].value_counts().head(20))

event_cause
vehicle_breakdown       4896
others                   638
pot_holes                537
construction             480
water_logging            458
accident                 365
tree_fall                284
road_conditions          170
congestion               136
public_event              84
procession                72
vip_movement              20
protest                   15
debris                    13
test_demo                  3
fog / low visibility       2
Name: count, dtype: int64

In [14]:
df['client_id'].value_counts()

client_id
1    8093
2      80
Name: count, dtype: int64

In [15]:
dropit=['id','kgid','client_id','client_id', 'created_by_id',
       'last_modified_by_id', 'closed_by_id']
df = df.drop(columns=dropit)

In [16]:
df['gba_identifier'].value_counts()

gba_identifier
Bengaluru Central Corporation    892
Bengaluru West Corporation       791
Bengaluru North Corporation      731
Bengaluru South Corporation      587
Bengaluru East Corporation       443
Name: count, dtype: int64

In [17]:
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent.sort_values(ascending=False))

end_datetime             94.004649
junction                 69.289123
closed_datetime          61.568579
zone                     57.861250
gba_identifier           57.861250
veh_no                   40.217790
veh_type                 40.205555
description              16.640157
endlongitude              2.067784
endlatitude               2.067784
corridor                  0.244708
address                   0.036706
priority                  0.024471
event_type                0.000000
latitude                  0.000000
longitude                 0.000000
requires_road_closure     0.000000
event_cause               0.000000
status                    0.000000
authenticated             0.000000
modified_datetime         0.000000
start_datetime            0.000000
police_station            0.000000
created_date              0.000000
dtype: float64

In [18]:
df['zone'].value_counts()

zone
Central Zone 2    623
West Zone 1       433
North Zone 2      413
West Zone 2       358
South Zone 2      354
North Zone 1      318
Central Zone 1    269
East Zone 1       253
South Zone 1      233
East Zone 2       190
Name: count, dtype: int64

In [19]:
df.groupby('gba_identifier')['zone'].nunique()

gba_identifier
Bengaluru Central Corporation    2
Bengaluru East Corporation       2
Bengaluru North Corporation      2
Bengaluru South Corporation      2
Bengaluru West Corporation       2
Name: zone, dtype: int64

In [20]:
df[(df['zone'].isna()) & (df['gba_identifier'].notna())].shape

(0, 24)

In [21]:
df['authenticated'].value_counts()

authenticated
yes    7166
no     1007
Name: count, dtype: int64

In [22]:
df=df.drop(columns=['gba_identifier','veh_no','status'])

In [23]:
df['authenticated'] = df['authenticated'].map({'yes': 1, 'no': 0, 'Yes': 1, 'No': 0})

In [24]:
datetime_cols = [
    'start_datetime',
    'created_date',
    'modified_datetime',
    'closed_datetime',
    'end_datetime'
]

for col in datetime_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

In [25]:
df['hour'] = df['start_datetime'].dt.hour
df['dayofweek'] = df['start_datetime'].dt.dayofweek
df['month'] = df['start_datetime'].dt.month
df['is_weekend'] = df['dayofweek'].isin([5, 6]).astype(int)
df['is_peak_hour'] = df['hour'].isin([8,9,10,17,18,19]).astype(int)

In [26]:
df['junction'].value_counts()

junction
MekhriCircle              64
AyyappaTempleJunc         49
SatteliteBusStandJunc     43
YeshwanthpuraCircle       38
YelhankaCircle            34
                          ..
K G Junction               1
Geeta Circle               1
BrigadeMillenium           1
NagaTheaterJunc-Ulsoor     1
SafinaPlazaJunc            1
Name: count, Length: 294, dtype: int64

In [27]:
df['end_datetime'].notna().sum()

np.int64(475)

In [28]:
df['closed_datetime'].notna().sum()

np.int64(3141)

In [29]:
((df['end_datetime'].notna()) & (df['closed_datetime'].notna())).sum()

np.int64(34)

In [30]:
temp = df[
    df['end_datetime'].notna() &
    df['closed_datetime'].notna()
].copy()

temp['gap_mins'] = (
    pd.to_datetime(temp['end_datetime']) -
    pd.to_datetime(temp['closed_datetime'])
).dt.total_seconds()/60

temp['gap_mins'].describe()
# discarded

count       34.000000
mean      3559.353416
std      11680.720926
min     -20287.406082
25%         -1.681912
50%         65.089996
75%        999.301494
max      45739.680484
Name: gap_mins, dtype: float64

In [31]:
df=df.drop(columns=['end_datetime','closed_datetime'])

In [32]:
df1=df
df1['report_delay']=(
    pd.to_datetime(df1['created_date']) -
    pd.to_datetime(df1['start_datetime'])
).dt.total_seconds()/60
#discarded

In [33]:
df.groupby('event_type')['report_delay'].describe()

,count,mean,std,min,25%,50%,75%,max
event_type,,,,,,,,
planned,365.0,2.574606,3.207016,-3.421940,1.032949,1.705095,3.130447,39.838228
unplanned,7692.0,3.789914,25.383229,-1421.077904,1.007850,1.517508,2.482710,405.712413

In [34]:
df=df.drop(columns=['created_date','modified_datetime','start_datetime','description','address','report_delay'])

In [35]:
df['priority'] = df['priority'].fillna(df['priority'].mode()[0])

In [36]:
df['endlatitude'] = df['endlatitude'].fillna(df['latitude'])
df['endlongitude']=df['endlongitude'].fillna(df['longitude'])

In [37]:
df = df.dropna(subset=['hour', 'dayofweek', 'month'])

In [38]:
df['veh_type'] = df['veh_type'].fillna('Unknown')

In [39]:
df1 = df.copy()
df1=df1.drop(columns='junction')
from sklearn.neighbors import KNeighborsClassifier
station_zone_map = (
    df1[df1['zone'].notna()]
    .groupby('police_station')['zone']
    .agg(lambda x: x.mode()[0] if not x.mode().empty else None)
    .dropna()
    .to_dict()
)

mask = df1['zone'].isna()

for idx in df1[mask].index:
    station = df1.loc[idx, 'police_station']
    
    if station in station_zone_map:
        df1.loc[idx, 'zone'] = station_zone_map[station]

known = df1[df1['zone'].notna()]
unknown = df1[df1['zone'].isna()]

if not unknown.empty:
    X_train = known[['latitude', 'longitude']]
    y_train = known['zone']

    X_test = unknown[['latitude', 'longitude']]

    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    df1.loc[df1['zone'].isna(), 'zone'] = pred
    
df1['zone'] = df1['zone'].fillna(df1['zone'].mode()[0])

known = df1[df1['corridor'].notna()]
unknown = df1[df1['corridor'].isna()]

X_train = known[['latitude', 'longitude']]
y_train = known['corridor']

X_test = unknown[['latitude', 'longitude']]

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

pred = knn.predict(X_test)

df1.loc[df1['corridor'].isna(), 'corridor'] = pred
df1['corridor'] = df1['corridor'].fillna(df1['corridor'].mode()[0])

In [40]:
missing_percent = (df1.isnull().sum() / len(df1)) * 100
print(missing_percent.sort_values(ascending=False))

event_type               0.0
latitude                 0.0
longitude                0.0
endlatitude              0.0
endlongitude             0.0
event_cause              0.0
requires_road_closure    0.0
authenticated            0.0
veh_type                 0.0
corridor                 0.0
priority                 0.0
police_station           0.0
zone                     0.0
hour                     0.0
dayofweek                0.0
month                    0.0
is_weekend               0.0
is_peak_hour             0.0
dtype: float64

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.utils.class_weight import compute_class_weight
from catboost import CatBoostClassifier

df1['target'] = df1['requires_road_closure'].astype(int)
features = [
    'event_type',
    'latitude',
    'longitude',
    'event_cause',
    'authenticated',
    'veh_type',
    'corridor',
    'priority',
    'police_station',
    'zone',
    'hour',
    'dayofweek',
    'month',
    'is_weekend',
    'is_peak_hour'
]
df_model = df1[features + ['target']].copy()
categorical_features = [
    'event_type',
    'event_cause',
    'veh_type',
    'corridor',
    'priority',
    'police_station',
    'zone',
]
X = df_model.drop(columns=['target'])
y = df_model['target']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))
print(class_weights)
cat_feature_indices = [X.columns.get_loc(col) for col in categorical_features]
model = CatBoostClassifier(
    iterations=700,
    depth=8,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='AUC',
    class_weights=class_weights,
    verbose=100,
    random_seed=42
)
model.fit(
    X_train,
    y_train,
    cat_features=cat_feature_indices,
    eval_set=(X_test, y_test),
    use_best_model=True
)
preds = model.predict(X_test)
probs = model.predict_proba(X_test)[:, 1]

threshold = 0.2
custom_preds = (probs >= threshold).astype(int)

print(classification_report(y_test, custom_preds))
print(confusion_matrix(y_test, custom_preds))
print("ROC AUC:", roc_auc_score(y_test, probs))
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.get_feature_importance()
}).sort_values(by='importance', ascending=False)

print(feature_importance)
sample = X_test.iloc[[0]]
closure_probability = model.predict_proba(sample)[0][1]

print("Road Closure Probability:", closure_probability)

{np.int64(0): np.float64(0.5399631367292225), np.int64(1): np.float64(6.755765199161425)}
0:	test: 0.7695323	best: 0.7695323 (0)	total: 71.7ms	remaining: 50.1s
100:	test: 0.8035032	best: 0.8054732 (47)	total: 1.41s	remaining: 8.38s
200:	test: 0.8055463	best: 0.8085323 (165)	total: 2.8s	remaining: 6.96s
300:	test: 0.8102855	best: 0.8106514 (292)	total: 4.34s	remaining: 5.75s
400:	test: 0.8122386	best: 0.8130210 (378)	total: 5.88s	remaining: 4.38s
500:	test: 0.8146701	best: 0.8148728 (494)	total: 7.45s	remaining: 2.96s
600:	test: 0.8146758	best: 0.8162799 (569)	total: 8.99s	remaining: 1.48s
699:	test: 0.8111073	best: 0.8162799 (569)	total: 10.5s	remaining: 0us

bestTest = 0.8162798944
bestIteration = 569

Shrink model to first 570 iterations.
              precision    recall  f1-score   support

           0       0.97      0.83      0.90      1493
           1       0.25      0.69      0.36       119

    accuracy                           0.82      1612
   macro avg       0.61      0.76      0.63      1612
weighted avg       0.92      0.82      0.86      1612

[[1243  250]
 [  37   82]]
ROC AUC: 0.8162798944092038
           feature  importance
8   police_station   13.206928
10            hour   10.435285
6         corridor   10.360993
9             zone   10.049777
5         veh_type   10.018558
2        longitude    9.494360
1         latitude    9.003818
3      event_cause    7.847479
12           month    7.793485
11       dayofweek    7.478974
14    is_peak_hour    1.285702
13      is_weekend    0.971817
7         priority    0.944960
4    authenticated    0.751772
0       event_type    0.356092
Road Closure Probability: 0.2687463580042258

In [44]:
missing_percent = (df1.isnull().sum() / len(df1)) * 100
print(missing_percent.sort_values(ascending=False))

event_type               0.0
latitude                 0.0
longitude                0.0
endlatitude              0.0
endlongitude             0.0
event_cause              0.0
requires_road_closure    0.0
authenticated            0.0
veh_type                 0.0
corridor                 0.0
priority                 0.0
police_station           0.0
zone                     0.0
hour                     0.0
dayofweek                0.0
month                    0.0
is_weekend               0.0
is_peak_hour             0.0
target                   0.0
dtype: float64

In [45]:
df1['closure_probability'] = model.predict_proba(df1[features])[:, 1]

df1['has_end_coords'] = (
    (df1['endlatitude'].notna()) &
    (df1['endlongitude'].notna()) &
    (df1['endlatitude'] != 0) &
    (df1['endlongitude'] != 0)
).astype(int)

df1['event_type'] = df1['event_type'].astype(str).str.lower().str.strip()
df1['event_cause'] = df1['event_cause'].astype(str).str.lower().str.strip()
df1['corridor'] = df1['corridor'].astype(str).str.lower().str.strip()
df1['zone'] = df1['zone'].astype(str).str.lower().str.strip()
df1['police_station'] = df1['police_station'].astype(str).str.lower().str.strip()

event_type_risk = {
    'planned': 0.45,
    'unplanned': 1.0
}

event_cause_risk = {
    'accident': 1.0,
    'vehicle_breakdown': 0.8,
    'water_logging': 0.95,
    'construction': 0.75,
    'tree_fall': 0.8,
    'congestion': 0.85,
    'public_event': 0.9,
    'procession': 0.95,
    'vip_movement': 0.8,
    'protest': 1.0,
    'pot_holes': 0.45,
    'road_conditions': 0.5,
    'others': 0.4
}

df1['event_type_risk'] = df1['event_type'].map(event_type_risk).fillna(0.5)
df1['event_cause_risk'] = df1['event_cause'].map(event_cause_risk).fillna(0.5)

corridor_risk_map = df1.groupby('corridor')['requires_road_closure'].mean().to_dict()
zone_risk_map = df1.groupby('zone')['requires_road_closure'].mean().to_dict()
station_risk_map = df1.groupby('police_station')['requires_road_closure'].mean().to_dict()

global_closure_mean = df1['requires_road_closure'].mean()

df1['corridor_risk'] = df1['corridor'].map(corridor_risk_map).fillna(global_closure_mean)
df1['zone_risk'] = df1['zone'].map(zone_risk_map).fillna(global_closure_mean)
df1['station_risk'] = df1['police_station'].map(station_risk_map).fillna(global_closure_mean)

def closure_risk(prob):
    if prob < 0.20:
        return 0.2
    elif prob < 0.40:
        return 0.5
    elif prob < 0.60:
        return 0.75
    return 1.0

df1['closure_risk'] = df1['closure_probability'].apply(closure_risk)

df1['time_risk'] = 0.2
df1.loc[df1['is_peak_hour'] == 1, 'time_risk'] += 0.5
df1.loc[df1['is_weekend'] == 1, 'time_risk'] += 0.15

night_mask = (df1['hour'] >= 21) | (df1['hour'] <= 6)
df1.loc[night_mask, 'time_risk'] += 0.15

df1['endpoint_risk'] = df1['has_end_coords'].map({
    0: 0.2,
    1: 0.8
})

df1['impact_score'] = (
    df1['closure_risk'] * 32 +
    df1['event_type_risk'] * 15 +
    df1['event_cause_risk'] * 20 +
    df1['corridor_risk'] * 10 +
    df1['zone_risk'] * 8 +
    df1['station_risk'] * 7 +
    df1['time_risk'] * 5 +
    df1['endpoint_risk'] * 3
)

df1['impact_score'] = df1['impact_score'].clip(0, 100)

low_thr = df1['impact_score'].quantile(0.60)
high_thr = df1['impact_score'].quantile(0.90)

def classify(score):
    if score <= low_thr:
        return 'Low'
    elif score <= high_thr:
        return 'Medium'
    return 'High'

df1['impact_class'] = df1['impact_score'].apply(classify)

print("Thresholds:")
print("Low <=", low_thr)
print("Medium <=", high_thr)

print(df1[['impact_score', 'impact_class']].head())
print(df1['impact_class'].value_counts())
print(df1['impact_score'].describe())

def predict_impact(sample):
    return {
        "impact_score": round(sample['impact_score'], 2),
        "impact_class": sample['impact_class']
    }

sample_output = predict_impact(df1.iloc[0])
print(sample_output)

Thresholds:
Low <= 42.68307335798369
Medium <= 54.80691386504076
   impact_score impact_class
0     42.520283          Low
1     41.484019          Low
2     45.270837       Medium
3     70.921343         High
4     52.520837       Medium
impact_class
Low       4834
Medium    2417
High       806
Name: count, dtype: int64
count    8057.000000
mean       44.016743
std         8.196321
min        27.263633
25%        40.809540
50%        42.073355
75%        44.451125
max        74.918456
Name: impact_score, dtype: float64
{'impact_score': np.float64(42.52), 'impact_class': 'Low'}

In [46]:
pip install osmnx

Collecting osmnx
  Downloading osmnx-2.1.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: geopandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from osmnx) (1.1.3)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from osmnx) (3.6.1)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.4.6)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.3.3)
Requirement already satisfied: requests>=2.30 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.32.4)
Requirement already satisfied: shapely>=2.0 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.1.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->osmnx) (1.17.0)
Downloading osmnx-2.1.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.4/104.4 kB 5.5 MB/s eta 0:00:00
Installing collected packages: osmnx
Successfully installed osmnx-2.1.0
Note: you may need to restart the kernel to use updated packages.

In [48]:
import networkx as nx
import osmnx as ox
G = ox.graph_from_place("Bengaluru, Karnataka, India", network_type="drive")

In [49]:
import requests

API_KEY = ""

df_rec = df1.copy()

major_nodes = [node for node in G.nodes() if G.degree(node) >= 3]


def get_route_mappls(source_lat, source_lon, dest_lat, dest_lon):
    positions = f"{source_lon},{source_lat};{dest_lon},{dest_lat}"

    url = f"https://route.mappls.com/route/direction/route_traffic/driving/{positions}"

    params = {
        "rtype": 0,
        "steps": True,
        "access_token": API_KEY
    }

    try:
        response = requests.get(url, params=params)
        data = response.json()

        if data["code"] != "Ok":
            return None

        route = data["routes"][0]

        roads = []
        if "legs" in route:
            for leg in route["legs"]:
                if "steps" in leg:
                    for step in leg["steps"]:
                        if "name" in step and step["name"]:
                            roads.append(step["name"])

        roads = list(dict.fromkeys(roads))

        return {
            "distance_m": route["distance"],
            "eta_min": route["duration"] / 60,
            "geometry": route.get("geometry"),
            "roads": roads
        }

    except:
        return None


def extract_road_names(route_nodes, G):
    roads = []

    for i in range(len(route_nodes) - 1):
        u = route_nodes[i]
        v = route_nodes[i + 1]

        try:
            edge_data = G.get_edge_data(u, v)

            if edge_data:
                edge = list(edge_data.values())[0]
                road_name = edge.get("name")

                if road_name:
                    if isinstance(road_name, list):
                        roads.extend(road_name)
                    else:
                        roads.append(road_name)
        except:
            continue

    roads = list(dict.fromkeys(roads))
    return roads


def get_best_diversion_route(row, G):
    incident_lat = row['latitude']
    incident_lon = row['longitude']

    try:
        source_node = ox.distance.nearest_nodes(G, incident_lon, incident_lat)
    except:
        return None

    if row['closure_probability'] > 0.8:
        blocked_radius = 0.010
    elif row['closure_probability'] > 0.5:
        blocked_radius = 0.006
    else:
        blocked_radius = 0.003

    candidate_nodes = []

    for node in major_nodes:
        if node == source_node:
            continue

        node_lat = G.nodes[node]['y']
        node_lon = G.nodes[node]['x']

        dist = ((node_lat - incident_lat)**2 + (node_lon - incident_lon)**2) ** 0.5

        if dist > blocked_radius:
            candidate_nodes.append((node, dist))

    candidate_nodes = sorted(candidate_nodes, key=lambda x: x[1])[:50]

    best_route = None
    best_distance = float('inf')
    best_target = None

    for target_node, _ in candidate_nodes:
        try:
            route = nx.shortest_path(G, source_node, target_node, weight='length')
            distance = nx.shortest_path_length(G, source_node, target_node, weight='length')

            if 800 <= distance <= 8000:
                if distance < best_distance:
                    best_distance = distance
                    best_route = route
                    best_target = target_node
        except:
            continue

    if best_route is None:
        return None

    dest_lat = G.nodes[best_target]['y']
    dest_lon = G.nodes[best_target]['x']

    validated = get_route_mappls(
        incident_lat,
        incident_lon,
        dest_lat,
        dest_lon
    )

    route_coords = []
    for node in best_route:
        route_coords.append((G.nodes[node]['y'], G.nodes[node]['x']))

    if validated:
        roads = validated["roads"]
        distance_m = validated["distance_m"]
        eta_min = validated["eta_min"]
        geometry = validated["geometry"]
    else:
        roads = extract_road_names(best_route, G)
        distance_m = best_distance
        eta_min = (best_distance / 1000) / 25 * 60
        geometry = None

    return {
        "route_nodes": best_route,
        "distance_m": distance_m,
        "eta_min": eta_min,
        "roads": roads,
        "route_coords": route_coords,
        "geometry": geometry
    }


def recommend_officers(row):
    officers = 2 if row['impact_class'] == 'Low' else 4 if row['impact_class'] == 'Medium' else 6

    if row['is_peak_hour'] == 1:
        officers += 2

    if row['event_cause'] in ['accident', 'vehicle_breakdown', 'tree_fall']:
        officers += 2

    if row['event_cause'] in ['public_event', 'procession', 'protest']:
        officers += 4

    if row['closure_probability'] > 0.7:
        officers += 2

    if row['has_end_coords'] == 1:
        officers += 1

    return officers


def recommend_barricades(row):
    barricades = 1 if row['impact_score'] < 45 else 3 if row['impact_score'] < 58 else 5

    if row['closure_probability'] > 0.75:
        barricades += 2

    if row['has_end_coords'] == 1:
        barricades += 1

    return barricades


def response_priority(row):
    if row['impact_class'] == 'High':
        return 'Immediate'
    elif row['impact_class'] == 'Medium':
        return 'High'
    return 'Normal'


def diversion_strategy(row):
    prob = row['closure_probability']

    if prob > 0.75:
        return 'Full Diversion Required'
    elif prob > 0.4:
        return 'Partial Diversion Recommended'
    return 'Traffic Monitoring Only'


def eta_target(row):
    if row['response_priority'] == 'Immediate':
        return '5 mins'
    elif row['response_priority'] == 'High':
        return '15 mins'
    return '30 mins'


def resource_plan(row):
    patrol = max(1, row['recommended_officers'] // 4)

    ambulance = row['event_cause'] == 'accident'
    crane = row['event_cause'] in ['vehicle_breakdown', 'tree_fall']

    return {
        "officers": int(row['recommended_officers']),
        "barricades": int(row['barricades_required']),
        "patrol_vehicles": patrol,
        "ambulance_required": ambulance,
        "crane_required": crane
    }


def traffic_forecast(row):
    delay = (
        row['closure_probability'] * 25 +
        row['impact_score'] * 0.18 +
        row['is_peak_hour'] * 8 +
        row['has_end_coords'] * 5
    )

    if delay >= 25:
        severity = "Severe"
    elif delay >= 12:
        severity = "Moderate"
    else:
        severity = "Minor"

    return {
        "severity": severity,
        "expected_delay_mins": round(delay, 1)
    }


df_rec['recommended_officers'] = df_rec.apply(recommend_officers, axis=1)
df_rec['barricades_required'] = df_rec.apply(recommend_barricades, axis=1)
df_rec['response_priority'] = df_rec.apply(response_priority, axis=1)
df_rec['diversion_strategy'] = df_rec.apply(diversion_strategy, axis=1)
df_rec['eta_target'] = df_rec.apply(eta_target, axis=1)


def generate_recommendation(row, G):
    recommendation = {
        "impact_score": round(row['impact_score'], 2),
        "impact_class": row['impact_class'],
        "closure_probability": round(row['closure_probability'], 3),
        "resource_plan": resource_plan(row),
        "traffic_forecast": traffic_forecast(row),
        "response_priority": row['response_priority'],
        "eta_target": row['eta_target'],
        "diversion_strategy": row['diversion_strategy']
    }

    if row['closure_probability'] < 0.4:
        return recommendation

    diversion = get_best_diversion_route(row, G)

    if diversion is not None:
        roads = diversion["roads"]

        recommendation["diversion_plan"] = {
            "best_diversion_distance_km": round(diversion["distance_m"] / 1000, 2),
            "best_diversion_eta_mins": round(diversion["eta_min"], 2),
            "diversion_road_name": roads[0] if len(roads) > 0 else None,
            "alternate_roads": roads[1:4] if len(roads) > 1 else [],
            "route_nodes": diversion["route_nodes"],
            "route_coords": diversion["route_coords"],
            "geometry": diversion["geometry"]
        }

    return recommendation


for idx, row in df_rec.head(10).iterrows():
    print(f"\nProcessing Index: {idx}")
    result = generate_recommendation(row, G)
    print(result)

Processing Index: 0
{'impact_score': 42.52, 'impact_class': 'Low', 'closure_probability': 0.03, 'resource_plan': {'officers': 6, 'barricades': 1, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 16.4}, 'response_priority': 'Normal', 'eta_target': '30 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 1
{'impact_score': 41.48, 'impact_class': 'Low', 'closure_probability': 0.1, 'resource_plan': {'officers': 4, 'barricades': 1, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Minor', 'expected_delay_mins': 10.0}, 'response_priority': 'Normal', 'eta_target': '30 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 2
{'impact_score': 45.27, 'impact_class': 'Medium', 'closure_probability': 0.372, 'resource_plan': {'officers': 4, 'barricades': 3, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': False}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 17.5}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 3
{'impact_score': 70.92, 'impact_class': 'High', 'closure_probability': 0.97, 'resource_plan': {'officers': 13, 'barricades': 8, 'patrol_vehicles': 3, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Severe', 'expected_delay_mins': 50.0}, 'response_priority': 'Immediate', 'eta_target': '5 mins', 'diversion_strategy': 'Full Diversion Required', 'diversion_plan': {'best_diversion_distance_km': np.float64(1.34), 'best_diversion_eta_mins': np.float64(3.21), 'diversion_road_name': 'Sankey Road', 'alternate_roads': ['Sankey Underpass', 'Sankey Road Flyover'], 'route_nodes': [10003979588, 3023900547, 3023900546, 4849094103, 4044342169, 1435578873, 2630925128], 'route_coords': [(13.0063329, 77.5790527), (13.0054129, 77.5806358), (13.0043711, 77.5823843), (13.0030076, 77.5840754), (13.0027849, 77.5841524), (12.9987459, 77.5842743), (12.9970153, 77.5845972)], 'geometry': None}}

Processing Index: 4
{'impact_score': 52.52, 'impact_class': 'Medium', 'closure_probability': 0.269, 'resource_plan': {'officers': 6, 'barricades': 3, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 16.2}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 5
{'impact_score': 47.82, 'impact_class': 'Medium', 'closure_probability': 0.04, 'resource_plan': {'officers': 7, 'barricades': 4, 'patrol_vehicles': 1, 'ambulance_required': True, 'crane_required': False}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 14.6}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 6
{'impact_score': 52.26, 'impact_class': 'Medium', 'closure_probability': 0.206, 'resource_plan': {'officers': 6, 'barricades': 3, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 14.5}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 7
{'impact_score': 51.77, 'impact_class': 'Medium', 'closure_probability': 0.45, 'resource_plan': {'officers': 4, 'barricades': 3, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': False}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 20.6}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Partial Diversion Recommended', 'diversion_plan': {'best_diversion_distance_km': np.float64(0.82), 'best_diversion_eta_mins': np.float64(1.97), 'diversion_road_name': "Saint Mark's Road", 'alternate_roads': ['Vittal Mallya Road', 'Lavelle Road'], 'route_nodes': [248459838, 248459827, 1492519184, 248459829, 1842803351, 1842803356, 10060517433, 248459840, 13821898844], 'route_coords': [(12.9730942, 77.6010663), (12.9727994, 77.6012741), (12.9722475, 77.6011495), (12.9703365, 77.6007447), (12.97075, 77.5992977), (12.9709487, 77.5986032), (12.971127, 77.5979803), (12.9712043, 77.5977545), (12.9697962, 77.597521)], 'geometry': None}}

Processing Index: 9
{'impact_score': 42.04, 'impact_class': 'Low', 'closure_probability': 0.192, 'resource_plan': {'officers': 4, 'barricades': 1, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': True}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 12.4}, 'response_priority': 'Normal', 'eta_target': '30 mins', 'diversion_strategy': 'Traffic Monitoring Only'}

Processing Index: 10
{'impact_score': 46.54, 'impact_class': 'Medium', 'closure_probability': 0.016, 'resource_plan': {'officers': 6, 'barricades': 3, 'patrol_vehicles': 1, 'ambulance_required': False, 'crane_required': False}, 'traffic_forecast': {'severity': 'Moderate', 'expected_delay_mins': 16.8}, 'response_priority': 'High', 'eta_target': '15 mins', 'diversion_strategy': 'Traffic Monitoring Only'}